kind: Deployment
apiVersion: apps/v1
metadata:
    name: mydeployment
spec: 
    replicas: 2
    selector: 
        matchLables:
            app: myspringbootapp
    template:
        metadata:
            lables: 
                app: myspringbootapp   
        spec:
            containers:
                - name: myspringbootapp
                  image: raghu350/mydemoapplication:latest
                  imagePullPolicy: Always
                  ports:
                    - containerPort: 9099
